"""What we ask Gemini about a clip, and the shape of the answer.

Bump `PROMPT_VERSION` when the wording changes. Cached answers are keyed on it,
so leaving it alone means serving answers produced by a prompt that no longer
exists.
"""

from __future__ import annotations

PROMPT_VERSION = "clearance-media-v1"

# Deliberately narrow. We ask what is *perceptible* in the file and nothing
# else: no identity, no guess at whether it was generated, no opinion about
# whether it may be used. Each of those would be a claim we cannot stand behind,
# and the product's whole boundary is that we prove permission rather than
# detect fakery.
INSTRUCTION = """You are examining one media file supplied by a film production's vendor.

Report only what is perceptible in the file itself.

- `modality`: `voice` if a human voice is audible, `face` if a human face is
  visible, `performance` if the file carries a whole visible performance of a
  person (face and body together), `none` if no person is perceptible.
- `human_present`: true only if a person is actually audible or visible.
- `description`: one plain sentence, at most 200 characters, describing what is
  in the file. Describe the content, not your opinion of it.
- `confidence`: 0 to 1, how sure you are of `modality`.

Three things you must not do, because we cannot stand behind them:

1. Do not name or guess who the person is. You are not being asked to identify
   anyone, and an identification here would be presented to a lawyer as fact.
2. Do not judge whether the file was generated by AI. Nothing downstream uses
   such a judgement.
3. Do not comment on whether the material may be used. That question is answered
   by contract records you cannot see.

If the file is unreadable or contains no person, say so through the fields:
`modality` `none`, `human_present` false. That is a useful answer, not a
failure."""

MODALITIES = ("voice", "face", "performance", "none")

RESPONSE_SCHEMA: dict = {
    "type": "object",
    "properties": {
        "modality": {"type": "string", "enum": list(MODALITIES)},
        "human_present": {"type": "boolean"},
        "description": {"type": "string"},
        "confidence": {"type": "number"},
    },
    "required": ["modality", "human_present", "description", "confidence"],
}

# What we accept for an inline read. Anything else is refused before a model
# call, because an unsupported type comes back as an unhelpful API error and the
# person uploading deserves a sentence they can act on.
ACCEPTED_MIME = {
    "audio/wav": "wav",
    "audio/x-wav": "wav",
    "audio/mpeg": "mp3",
    "audio/mp3": "mp3",
    "audio/aac": "aac",
    "audio/flac": "flac",
    "audio/ogg": "ogg",
    "video/mp4": "mp4",
    "video/quicktime": "mov",
    "video/webm": "webm",
    "image/jpeg": "jpg",
    "image/png": "png",
    "image/webp": "webp",
}

# Vertex takes inline bytes up to roughly 20 MB. Past that the file has to go
# through the Files API, which is not built — so we refuse with a clear reason
# instead of failing deep inside the client.
MAX_INLINE_BYTES = 18 * 1024 * 1024
