"""WU-20 — warm the cache so the demo cannot need the network.

    python tools/warm_demo_cache.py                 # sweep + read + verdict
    python tools/warm_demo_cache.py --check         # verify a warm cache
    python tools/warm_demo_cache.py --performer perf_mira_vance

Runs the **real** pipeline once against the real services and writes every
answer to a cache on disk. Then `DEMO_MODE=true` replays it with zero external
calls.

Why bother: the video shoot cannot die on a rate limit at 1am the night before
submission. This is roughly an hour of work against that, and `--check` means
nobody has to *hope* the cache is warm — they can ask.

**It writes to `CACHE_DIR` (default `./.cache`) as JSON.** WU-19 is Prachit's
Firestore-and-GCS cache; when it lands, pass it in via `HarnessDeps(cache=...)`
and delete `JsonFileCache` below. The on-disk format is deliberately dull for
exactly that reason — it is a stopgap, not an interface.

What is cached, and by which key:

| Client          | Key                                        |
|-----------------|--------------------------------------------|
| `parallel_search` | queries + locale + mode + settings, 6h TTL |
| `web_risk_check`  | the URL, 6h TTL                            |
| `fetch_page`      | URL + locale + size cap, 6h TTL            |
| `Triage`          | sha256(page text) + prompt_version, no TTL |

Verdicts are absent on purpose: hard rule 7, never cache a verdict. The
reconciler recomputes on read, which costs nothing.
"""

from __future__ import annotations

import argparse
import json
import logging
import pickle
import sys
from base64 import b64decode, b64encode
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from consentinel.agents.query_planner import (  # noqa: E402
    QueryPlanner,
    deterministic_plan,
)
from consentinel.agents.reconciler import Reconciler  # noqa: E402
from consentinel.agents.text_sweep import TextSweep  # noqa: E402
from consentinel.agents.triage import Triage  # noqa: E402
from consentinel.demo_mode import ENV_VAR, is_enabled  # noqa: E402
from consentinel.harness import HarnessDeps, MemoryAudit  # noqa: E402
from consentinel.harness.ports import CacheHit  # noqa: E402
from consentinel.store.base import Consent, Performer  # noqa: E402
from consentinel.tools.fetch_page import PageFetcher  # noqa: E402
from consentinel.tools.web_risk import WebRiskCheck  # noqa: E402

log = logging.getLogger("warm_demo_cache")

SEED = ROOT / "fixtures" / "seed.json"
DEFAULT_CACHE_DIR = ROOT / ".cache"


class JsonFileCache:
    """A `CachePort` on disk. Stopgap until WU-19 (see the module docstring).

    One file per entry, named by a hash of the key, holding the pickled value
    and the timestamp. Pickle because the cached values are our own dataclasses
    and this file is not a wire format — it never leaves the machine, and it is
    regenerated by re-running this script.
    """

    def __init__(self, directory: Path) -> None:
        self.dir = directory
        self.dir.mkdir(parents=True, exist_ok=True)
        self.writes = 0
        self.hits = 0
        self.misses = 0

    def _path(self, key: str) -> Path:
        import hashlib
        return self.dir / f"{hashlib.sha256(key.encode('utf-8')).hexdigest()}.json"

    def get(self, key: str) -> Optional[CacheHit]:
        path = self._path(key)
        if not path.exists():
            self.misses += 1
            return None
        try:
            blob = json.loads(path.read_text(encoding="utf-8"))
            value = pickle.loads(b64decode(blob["value"]))  # noqa: S301 - our own file
            fetched_at = datetime.fromisoformat(blob["fetched_at"])
        except Exception as exc:  # noqa: BLE001 - a corrupt entry is a miss
            log.warning("cache entry %s unreadable (%s); treating as a miss",
                        path.name, exc)
            self.misses += 1
            return None
        ttl = blob.get("ttl_seconds")
        if ttl is not None:
            age = (datetime.now(timezone.utc) - fetched_at).total_seconds()
            if age > ttl:
                self.misses += 1
                return None
        self.hits += 1
        return CacheHit(value=value, fetched_at=fetched_at)

    def put(self, key: str, value: Any, ttl_seconds: Optional[int]) -> None:
        try:
            payload = b64encode(pickle.dumps(value)).decode("ascii")
        except Exception as exc:  # noqa: BLE001 - unpicklable: skip, do not crash
            log.warning("not caching %s: %s", key[:60], exc)
            return
        self._path(key).write_text(json.dumps({
            "key": key, "value": payload, "ttl_seconds": ttl_seconds,
            "fetched_at": datetime.now(timezone.utc).isoformat(),
        }), encoding="utf-8")
        self.writes += 1

    def entries(self) -> int:
        return len(list(self.dir.glob("*.json")))


class NullStore:
    """The sweep wants a store; warming does not want to touch the registry."""

    def __init__(self) -> None:
        self.rows: dict[str, Any] = {}

    def upsert_finding(self, finding: Any) -> Any:
        self.rows[finding.url_hash] = finding
        return finding


def load_seed(performer_id: str) -> tuple[Performer, list[Consent]]:
    data = json.loads(SEED.read_text(encoding="utf-8"))
    performers = {p["id"]: p for p in data.get("performers", [])}
    if performer_id not in performers:
        raise SystemExit(f"no performer {performer_id!r} in {SEED}; "
                         f"have: {', '.join(performers)}")
    raw = performers[performer_id]
    performer = Performer(id=raw["id"], name=raw["name"],
                          aliases=list(raw.get("aliases", [])),
                          reference_images=list(raw.get("reference_images", [])))
    consents = [
        Consent(id=c["id"], performer_id=c["performer_id"],
                licensee=c["licensee"],
                permitted_uses=list(c.get("permitted_uses", [])),
                territories=list(c.get("territories", [])))
        for c in data.get("consents", [])
        if c.get("performer_id") == performer_id
    ]
    return performer, consents


def warm(performer_id: str, cache_dir: Path, *, use_model_planner: bool
         ) -> int:
    """Run the pipeline live and record everything it asks for."""
    if is_enabled():
        raise SystemExit(
            f"{ENV_VAR}=true — this script must run live to fill the cache. "
            f"Unset {ENV_VAR} and try again.")

    performer, consents = load_seed(performer_id)
    cache = JsonFileCache(cache_dir)
    deps = HarnessDeps(cache=cache, audit=MemoryAudit())

    # 1 — the plan. The model version costs one call; the deterministic one is
    # free and equally cacheable downstream.
    plan = (QueryPlanner(deps=deps).plan(performer, consents)
            if use_model_planner else deterministic_plan(performer, consents))
    log.info("plan: %d batches, %d locales, degraded=%s",
             len(plan.batches), len(plan.locales), plan.degraded)

    # 2 — the sweep. Every parallel_search call lands in the cache.
    sweep = TextSweep(store=NullStore(), deps=deps)
    report = sweep.run(performer, plan)
    log.info("sweep: %d findings, %d raw, degraded=%s",
             len(report.findings), report.raw_results, report.degraded)
    if report.degraded:
        log.warning("sweep was degraded: %s", report.abort_reason
                    or list(report.batches_degraded))

    # 3 — read every candidate: web_risk, fetch_page and Triage all cache.
    fetcher = PageFetcher(deps=deps, risk=WebRiskCheck(deps=deps))
    triage = Triage(deps=deps)
    reconciler = Reconciler(deps=deps)
    read = refused = 0
    for candidate in report.candidates:
        outcome = fetcher.fetch_detailed(candidate.url, candidate.locale,
                                         subject_id=performer.id)
        if not outcome.ok or outcome.snapshot is None:
            refused += 1
            log.info("skipped %s (%s)", candidate.url, outcome.reason)
            continue
        reading = triage.read(outcome.snapshot, performer)
        if reading.ok and reading.extraction:
            read += 1
            # Not cached (hard rule 7) — run anyway, so a warm demo exercises
            # the same code path and any crash shows up now rather than on
            # camera.
            reconciler.for_extraction(reading.extraction, performer.id,
                                      consents, actor=None)

    log.info("read %d pages, %d refused; cache now holds %d entries "
             "(%d written this run)", read, refused, cache.entries(),
             cache.writes)
    print(f"\nwarm: {cache.entries()} entries in {cache_dir}")
    print(f"now run the demo with {ENV_VAR}=true")
    return 0 if read else 1


def check(performer_id: str, cache_dir: Path) -> int:
    """Replay the pipeline with `DEMO_MODE=true` and report what is missing."""
    import os

    os.environ[ENV_VAR] = "true"
    performer, consents = load_seed(performer_id)
    cache = JsonFileCache(cache_dir)
    deps = HarnessDeps(cache=cache, audit=MemoryAudit())

    plan = deterministic_plan(performer, consents)
    report = TextSweep(store=NullStore(), deps=deps).run(performer, plan)

    fetcher = PageFetcher(deps=deps, risk=WebRiskCheck(deps=deps))
    triage = Triage(deps=deps)
    readable = 0
    for candidate in report.candidates:
        outcome = fetcher.fetch_detailed(candidate.url, candidate.locale)
        if outcome.ok and outcome.snapshot and triage.read(
                outcome.snapshot, performer).ok:
            readable += 1

    ok = not report.degraded and readable == len(report.candidates) and readable
    print(f"cache: {cache.entries()} entries, {cache.hits} hits, "
          f"{cache.misses} misses")
    print(f"sweep: {len(report.findings)} findings, degraded={report.degraded}")
    print(f"pages readable from cache: {readable}/{len(report.candidates)}")
    print("WARM" if ok else "COLD — run without --check to fill it")
    return 0 if ok else 1


def main() -> int:
    logging.basicConfig(level=logging.INFO,
                        format="%(asctime)s %(levelname)s %(message)s")
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--performer", default="perf_mira_vance")
    ap.add_argument("--cache-dir", type=Path, default=None,
                    help="defaults to CACHE_DIR from .env, else ./.cache")
    ap.add_argument("--check", action="store_true",
                    help="verify the cache instead of filling it")
    ap.add_argument("--model-planner", action="store_true",
                    help="use the Gemini QueryPlanner rather than the "
                         "deterministic plan (one extra model call)")
    args = ap.parse_args()

    try:
        from dotenv import load_dotenv
        load_dotenv(ROOT / ".env")
    except ImportError:
        pass

    import os

    cache_dir = args.cache_dir or Path(
        os.environ.get("CACHE_DIR", str(DEFAULT_CACHE_DIR)))

    if args.check:
        return check(args.performer, cache_dir)
    return warm(args.performer, cache_dir,
                use_model_planner=args.model_planner)


if __name__ == "__main__":
    raise SystemExit(main())
